repos:
  - repo: https://github.com/srstevenson/nb-clean
    rev: 3.3.0
    hooks:
      - id: nb-clean
        args:
          - -o
          - --remove-empty-cells
          - --preserve-cell-metadata
          - preserve
          - tags
          - --