icon_map = {
    "airplane": "fas fa-plane",
    "apple": "fas fa-apple-alt",
    "backpack": "fas fa-backpack",
    "banana": "fas fa-banana",
    "baseball bat": "fas fa-baseball-bat",
    "baseball glove": "fas fa-baseball",
    "bear": "fas fa-paw",
    "bed": "fas fa-bed",
    "bench": "fas fa-bench",
    "bicycle": "fas fa-bicycle",
    "bird": "fas fa-dove",
    "boat": "fas fa-ship",
    "book": "fas fa-book",
    "bottle": "fas fa-bottle-water",
    "bowl": "fas fa-bowl-food",
    "broccoli": "fas fa-seedling",
    "bus": "fas fa-bus",
    "cake": "fas fa-cake-candles",
    "car": "fas fa-car",
    "carrot": "fas fa-carrot",
    "cat": "fas fa-cat",
    "cell phone": "fas fa-mobile-alt",
    "chair": "fas fa-chair",
    "clock": "fas fa-clock",
    "couch": "fas fa-couch",
    "cow": "fas fa-cow",
    "cup": "fas fa-mug-hot",
    "dining table": "fas fa-utensils",
    "dog": "fas fa-dog",
    "donut": "fas fa-cookie",
    "elephant": "fas fa-elephant",
    "fire hydrant": "fas fa-fire-extinguisher",
    "fork": "fas fa-utensil-fork",
    "frisbee": "fas fa-circle",
    "giraffe": "fas fa-giraffe",
    "hair drier": "fas fa-wind",
    "handbag": "fas fa-shopping-bag",
    "horse": "fas fa-horse",
    "hot dog": "fas fa-hotdog",
    "keyboard": "fas fa-keyboard",
    "kite": "fas fa-wind",
    "knife": "fas fa-utensil-knife",
    "laptop": "fas fa-laptop",
    "microwave": "fas fa-microwave",
    "motorcycle": "fas fa-motorcycle",
    "mouse": "fas fa-computer-mouse",
    "orange": "fas fa-apple-whole",
    "oven": "fas fa-oven",
    "parking meter": "fas fa-parking",
    "person": "fas fa-user",
    "pizza": "fas fa-pizza-slice",
    "potted plant": "fas fa-seedling",
    "refrigerator": "fas fa-refrigerator",
    "remote": "fas fa-remote",
    "sandwich": "fas fa-burger",
    "scissors": "fas fa-scissors",
    "sheep": "fas fa-sheep",
    "sink": "fas fa-sink",
    "skateboard": "fas fa-skateboard",
    "skis": "fas fa-skiing",
    "snowboard": "fas fa-snowboarding",
    "spoon": "fas fa-utensil-spoon",
    "sports ball": "fas fa-baseball",
    "stop sign": "fas fa-octagon",
    "suitcase": "fas fa-suitcase",
    "surfboard": "fas fa-water",
    "teddy bear": "fas fa-teddy-bear",
    "tennis racket": "fas fa-table-tennis",
    "tie": "fas fa-user-tie",
    "toaster": "fas fa-bread-slice",
    "toilet": "fas fa-toilet",
    "toothbrush": "fas fa-toothbrush",
    "traffic light": "fas fa-traffic-light",
    "train": "fas fa-train",
    "truck": "fas fa-truck",
    "tv": "fas fa-tv",
    "umbrella": "fas fa-umbrella",
    "vase": "fas fa-vase",
    "wine glass": "fas fa-wine-glass-alt",
    "zebra": "fas fa-horse",
}