icon_map = {
    "airplane": "fas fa-plane",
    "apple": "fas fa-apple-alt",
    "backpack": "fas fa-backpack",
    "banana": "fas fa-lemon",
    "baseball bat": "fas fa-baseball-bat-ball",
    "baseball glove": "fas fa-hand-paper",
    "bear": "fas fa-paw",
    "bed": "fas fa-bed",
    "bench": "fas fa-couch",
    "bicycle": "fas fa-bicycle",
    "bird": "fas fa-dove",
    "boat": "fas fa-ship",
    "book": "fas fa-book",
    "bottle": "fas fa-wine-bottle",
    "bowl": "fas fa-utensil-spoon",
    "broccoli": "fas fa-seedling",
    "bus": "fas fa-bus",
    "cake": "fas fa-birthday-cake",
    "car": "fas fa-car",
    "carrot": "fas fa-carrot",
    "cat": "fas fa-cat",
    "cell phone": "fas fa-mobile-alt",
    "chair": "fas fa-chair",
    "clock": "fas fa-clock",
    "couch": "fas fa-couch",
    "cow": "fas fa-cow",
    "cup": "fas fa-coffee",
    "dining table": "fas fa-utensils",
    "dog": "fas fa-dog",
    "donut": "fas fa-donut",
    "elephant": "fas fa-elephant",
    "fire hydrant": "fas fa-fire-extinguisher",
    "fork": "fas fa-utensil-fork",
    "frisbee": "fas fa-compact-disc",
    "hair drier": "fas fa-wind",
    "handbag": "fas fa-shopping-bag",
    "horse": "fas fa-horse",
    "hot dog": "fas fa-hotdog",
    "keyboard": "fas fa-keyboard",
    "kite": "fas fa-wind",
    "knife": "fas fa-utensil-knife",
    "laptop": "fas fa-laptop",
    "microwave": "fas fa-microwave",
    "motorcycle": "fas fa-motorcycle",
    "mouse": "fas fa-mouse",
    "orange": "fas fa-apple-alt",
    "oven": "fas fa-stove",
    "parking meter": "fas fa-parking",
    "person": "fas fa-user",
    "pizza": "fas fa-pizza-slice",
    "potted plant": "fas fa-seedling",
    "refrigerator": "fas fa-icicles",
    "remote": "fas fa-tv",
    "sandwich": "fas fa-bread-slice",
    "scissors": "fas fa-cut",
    "sheep": "fas fa-sheep",
    "sink": "fas fa-sink",
    "skateboard": "fas fa-skateboard",
    "skis": "fas fa-skiing",
    "snowboard": "fas fa-snowboarding",
    "spoon": "fas fa-utensil-spoon",
    "sports ball": "fas fa-futbol",
    "stop sign": "fas fa-octagon",
    "suitcase": "fas fa-suitcase",
    "surfboard": "fas fa-swimmer",
    "teddy bear": "fas fa-teddy-bear",
    "tennis racket": "fas fa-table-tennis",
    "tie": "fas fa-user-tie",
    "toilet": "fas fa-toilet",
    "toothbrush": "fas fa-tooth",
    "traffic light": "fas fa-traffic-light",
    "train": "fas fa-train",
    "truck": "fas fa-truck",
    "tv": "fas fa-tv",
    "umbrella": "fas fa-umbrella",
    "vase": "fas fa-flower",
    "wine glass": "fas fa-wine-glass-alt",
    "zebra": "fas fa-horse-head",
}
